### ISSUE TITLE
Moved "libs" directory

### ISSUE THREAD

**Issue by risingisland** [risingisland/Easy-2-Gallery#3]
@Breezer @Nicola1971

I started a new Dev. branch:

• Moved "assets/libs" directory into "assets/modules/easy2/libs"
Note: if upgrading from previous version, you will need to update Viewer, Slideshow, Plugin paths via the Main Menu.

• Created an Installer Package.

Two issues I would like to take care of:
1. How can a category be set to "Gallery" for the Plugin & Snippet?
File install.class.php, near lines 1166 & 1212.

2. I can not for the life of me get the mouseover icons to either float left or move down, so that the selection box is not on top of it. 
![image-mouseover-icons](https://cloud.githubusercontent.com/assets/6113504/21456039/dba08bde-c91c-11e6-9165-fbd710685c50.png)

**Comment by Nicola1971** [comment]
@risingisland 

added install tpl for easy2gallery_landingpage_comments and easy2gallery_view_processor snippets
https://github.com/risingisland/Easy-2-Gallery/pull/4

About plugins and snippet installed with Module setup.
I suggest to remove from https://github.com/risingisland/Easy-2-Gallery/blob/Development/assets/modules/easy2/install/index.php and create evo tpls

**Comment by Breezer** [comment]
Is there any documentation or examples on how to create the install tpls? I assume this format is used by the Extras module.

**Comment by risingisland** [comment]
In the Dev branch, I just added your two new Snippet templates.
Note: I changed their names slightly and added the changes to the ReadMe.

For template creation, I use a Module "[Make Install](https://github.com/Nicola1971/makeinstall-module)", which will export all TVs, Chunks, Snippets, etc. to a given folder. Then edit, if needed afterwords.

**Comment by Nicola1971** [comment]
@Breezer a basic documentation is here:
https://github.com/Jako/PackageManager

as @risingisland suggested,  you can use Make Install to export all tpls (but there are some issue with plugins export):
https://github.com/Nicola1971/makeinstall-module
or 
https://github.com/Nicola1971/Packager (again, issue with plugins : need to update parameters export for new evo json format)

@risingisland i don't know very well the module components and templates, where i can find "thumbnails/ icons" source/tpl?
 i wil try to fix your issue with checkbox
