### ISSUE TITLE
Moved Plugin & Snippet creation to Package installer

### ISSUE THREAD

**Issue by risingisland** [risingisland/Easy-2-Gallery#5]
@Breezer @Nicola1971

I just moved Plugin & Snippet creation to Package installer.

If you wouldn't mind, double check what I commented out before I remove in:
"assets\modules\easy2\install\index.php" & "install.class.php"

Just wanted to double check before I screw something up :wink:

PS: :gift: :evergreen_tree: Happy holidays :evergreen_tree: :gift:

**Comment by Breezer** [comment]
Ok i'll give it a once over here in the next day or so, it's really busy here at the moment prepping for xmas.

Happy Holidays to you too :)
