### ISSUE TITLE
Problem with thumbnails

### ISSUE THREAD

**Issue by yanqpl** [risingisland/Easy-2-Gallery#7]
Hi guys

I have a problem with thumbnails, when upload files, everything goes fine, but when i go to folder i see only one thumbnails, when i click zoom i see proper photo.

See my link below to look into module view
![10472182](https://cloud.githubusercontent.com/assets/24938064/22515202/fac84566-e8a1-11e6-8d8e-db0fd7e1504a.png)

This same problem on site preview
![10472191](https://cloud.githubusercontent.com/assets/24938064/22515176/ea2b6710-e8a1-11e6-8a1e-f708ca676079.png)

**Comment by risingisland** [comment]
That sounds familiar. 
Check that the "gallery" folder has proper permissions.
What version of e2g are you using?
Maybe grab the Dev branch.

**Comment by yanqpl** [comment]
Thanks for reply.

I'm using Easy 2 Gallery 1.5.3
Permissions are proper 755 for folder and 664 for file, the folder are writable and upload works fine.
But any thumbnails is not created. Screen below
![pobrane](https://cloud.githubusercontent.com/assets/24938064/22540326/d60cecee-e91f-11e6-880e-42705e88067d.png)

And have a look on missing dott before extension
![pobrane 3](https://cloud.githubusercontent.com/assets/24938064/22540475/a650aa58-e920-11e6-9e6f-c1df050c5236.png)


And another screen below  when i click zoom i see proper photo.
![pobrane 1](https://cloud.githubusercontent.com/assets/24938064/22540387/2664ca72-e920-11e6-9bb0-6a6529c92a7b.png)
![pobrane 2](https://cloud.githubusercontent.com/assets/24938064/22540386/26640984-e920-11e6-97fd-30205d8f3802.png)

**Comment by risingisland** [comment]
In settings/general, try shutting off the "permissions options" and "clear cache" when save.

![permissions](https://cloud.githubusercontent.com/assets/6113504/22543801/0986cc34-e92a-11e6-9317-2fc2e224edc0.png)

Then in Files, reSyncronize. See if that makes any difference.

**Comment by yanqpl** [comment]
I got this settings turned off ;/

**Comment by risingisland** [comment]
And did that make any difference or not?

**Comment by yanqpl** [comment]
No any difference.
Maybe its problem with missing dott?

When i change image size in module option one thumbnails was change
![pobrane](https://cloud.githubusercontent.com/assets/24938064/22545424/fcee11d0-e938-11e6-8ece-ec73583fdfc9.png)

**Comment by yanqpl** [comment]
Its only problem with thumbnails, see link and try to zoom any picture
http://okna-profil.pl/galeria.html

**Comment by risingisland** [comment]
Have you made any changes to the template or anything else?
Looking at the source, e2g doesnt seem to be outputting what it should:

![untitled](https://cloud.githubusercontent.com/assets/6113504/22546239/3245aae6-e934-11e6-9ee5-113430b3357a.png)

There should be a list of thumbs in there.

**Comment by yanqpl** [comment]
No any change was made, try to look at source again
http://okna-profil.pl/galeria.html

**Comment by risingisland** [comment]
Hmm, I am seeing that the thumbnail is missing the image name:
![name](https://cloud.githubusercontent.com/assets/6113504/22547328/202c3438-e939-11e6-8195-c99b4fc388b8.png)

It should be something like:
  `<img src="assets/images/gallery/_thumbnails/MY-IMAGE_inner_140x140_86_255x255x255.jpg" alt="MY-IMAGE" width="140" height="140" />`

By any chance, do some of the image file names contain Polish characters?

**Comment by yanqpl** [comment]
No i always rename file if contain Polish characters.
I got only 3 files in system already, as you can see on screen below (list view generate thumbnails)
![pobrane](https://cloud.githubusercontent.com/assets/24938064/22547572/8b42e538-e942-11e6-97c8-e086a505d39a.png)

**Comment by risingisland** [comment]
I see that in your image, the file extensions are missing the period before the JPG.
Maybe when renaming them, it was removed?
Change `hst85-3jpg` to `hst85-3.jpg` and so on...

**Comment by yanqpl** [comment]
But i upload files with period, module rename it automatic. I dont know why.

**Comment by risingisland** [comment]
Check via ftp if they are missing this. If so, fix, then via the gallery, re-sync and see if this clears up the problem.

**Comment by yanqpl** [comment]
But i can rename every files via ftp. Why upload module rename it?

**Comment by risingisland** [comment]
Did this fix the problem?
You are sure the images had period before upload?
Were the extensions in uppercase or lower case before upload?

I cant reproduce this problem on my end, so I am not sure what is causing this.

**Comment by yanqpl** [comment]
When i rename file via FTP and click "Rescan HD" thumbnails generate proper view.
![pobrane 1](https://cloud.githubusercontent.com/assets/24938064/22549542/1dea85b8-e94c-11e6-9cdf-f736df3b1c39.png)

When i add another file system rename all my files and delete period before extension.
![pobrane 2](https://cloud.githubusercontent.com/assets/24938064/22549567/3ae4a676-e94c-11e6-9116-209192ace5ef.png)


Click "Synchronize" do this same, rename all files ;/
The extension is lower case

**Comment by yanqpl** [comment]
And after i add many periods upload system still deleting it.
I try with all images extensions and with lower or upper case. It's pretty annoying,
I don't what is wrong with my server or E2G ;/

**Comment by risingisland** [comment]
I am looking through the [forum](https://forums.modx.com/index.php/board,415.0.html) to see if I can find the problem, as I think I remember seeing it before, but cant find the post...

**Comment by yanqpl** [comment]
I will be very grateful

**Comment by risingisland** [comment]
does it rename even the ones you have already changed via ftp?

**Comment by yanqpl** [comment]
Yes. It change every file in folder.

**Comment by risingisland** [comment]
I dont know if you solved this issue yet.
I'm still looking through the modx forum when I have free time.
Have you tried this on localhost, or anywhere else. I can not reproduce this problem.
You may want to check to see if magic_quotes is disabled or not. I dont remember if the install checks for this.

**Comment by yanqpl** [comment]
Thanks

I let you know when check this gallery on another hosting.
Installation checks magic_quotes status and it's disabled.

**Comment by yanqpl** [comment]
On my second hosting, everything works fine. Soo it sounds like problem of my my other hosting provider.

Thanks for help anyway :)

**Comment by risingisland** [comment]
Glad it is resolved. I hope you can figure out what php plugin is causing the problem.
Maybe you will be able to enable/disable it via a php.ini
